_task_name_cereal_coffee = 'Make cereal and coffee for breakfast'
_task_name_tea_eggs = 'Make tea and eggs for breakfast'
_task_name_toast_coffee = 'Make toast and coffee for breakfast'
_task_name_toast_eggs = 'Make toast and eggs for breakfast'
_task_name_yoghurt = 'Make yoghurt parfait for breakfast'
_task_name_cereal = 'Prepare cereal for breakfast'
_task_name_eggs = 'Prepare eggs for breakfast'
_task_name_omlette = 'Prepare omelette for breakfast'
_task_name_pancake = 'Make pancakes for breakfast'
_task_name_french = 'Make a french toast for breakfast'
_task_name_coffee_oatmeal = 'Make coffee and oatmeal for breakfast'
_task_name_tea_toast = 'Prepare tea and toast for breakfast'
_task_name_scrambled = 'Prepare scrambled eggs for breakfast'

savory = [_task_name_eggs, _task_name_omlette, _task_name_tea_eggs, _task_name_toast_eggs, _task_name_scrambled]
sweet = [_task_name_cereal, _task_name_yoghurt, _task_name_pancake, _task_name_french, _task_name_coffee_oatmeal, _task_name_cereal_coffee]
cereal = [_task_name_cereal_coffee, _task_name_cereal]
beverages = [_task_name_tea_toast, _task_name_toast_coffee, _task_name_coffee_oatmeal, _task_name_cereal_coffee, _task_name_tea_eggs]
tea = [_task_name_tea_eggs, _task_name_tea_toast]
coffee = [_task_name_cereal_coffee, _task_name_toast_coffee, _task_name_coffee_oatmeal]
eggs = [_task_name_eggs, _task_name_omlette, _task_name_scrambled, _task_name_tea_eggs, _task_name_toast_eggs]
toast = [_task_name_toast_coffee, _task_name_toast_eggs, _task_name_tea_toast]
oatmeal = [_task_name_coffee_oatmeal]
yoghurt = [_task_name_yoghurt]
cooked = savory + [_task_name_pancake, _task_name_french]
french_or_waffle_or_pancake = [_task_name_french, _task_name_pancake]
french_toast = [_task_name_french]
pancakes = [_task_name_pancake]
